require 'fileutils'

module Branches
  module Setup
    class << self
      def setup_config_repo(path, key)
        path = File.expand_path(path)
        key = File.expand_path(key)
        FileUtils.mkdir(path)
        Dir.chdir(path) do
          %x[git init]
          FileUtils.mkdir(File.join(path, 'keys'))
          FileUtils.cp(key, File.join(path, 'keys', 'admin'))
          open(File.join(path, 'config.rb'), 'w') do |f|
            f.write <<-EOS
Branches.config do
  keydir 'keys'

  global do |g|
    g.write = 'admin'
  end
end
EOS
          end
          %x[git add *]
          %x[git commit -m 'Initial configuration']
        end
      end

      def generate_authorized_keys(keys_path)
        File.mkdir(File.join(ENV['HOME'], '.ssh'))
        open(File.join(ENV['HOME'], '.ssh', 'authorized_keys'), 'w') do |f|
          f.write "### autogenerated by Branches"
          Dir.glob(File.join(keys_path, '*')) do |k|
            f.write "command=\"branches #{k}\",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty #{read(File.join(keys_path, k)).chomp}"
          end
        end
      end
    end # class
  end # Setup
end # Branches